[theme]
base = "light"
primaryColor = "#e78c3a"
backgroundColor = "#f3f2ee"
secondaryBackgroundColor = "#e9e5da"
textColor = "#262626"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true
